<?php
#####---=== Home page => counter settings ===--- #####
#####------------------------------------------- #####

//Home page settings -> Custom home page
real_estate_salient_pro_kirki::add_section( 'real_estate_salient_pro_home_counter', array(
    'title'          => esc_html__( 'Number counter', 'real-estate-salient-pro' ),
    'description'    => esc_html__( '', 'real-estate-salient-pro' ),
    'panel'          => 'real_estate_salient_pro_home',
    'priority'       => 8,
) );

// counter on off
real_estate_salient_pro_kirki::add_field( 'real_estate_salient_pro_counter', array(
    'type'        => 'radio-buttonset',
    'settings'    => 'counter_enable',
    'label'       => __( 'Number counter on / off', 'real-estate-salient-pro' ),
    'description' => __( 'Do you wish to show number counter?', 'real-estate-salient-pro' ),
    'section'     => 'real_estate_salient_pro_home_counter',
    'default'     => 'enable',
    'priority'    => 1,
    'choices'     => array(
        'enable'   => esc_attr__( 'Enable', 'real-estate-salient-pro' ),
        'disable' => esc_attr__( 'Disable', 'real-estate-salient-pro' ),
    ),
) );
// seperator
real_estate_salient_pro_kirki::add_field( 'real_estate_salient_pro_counter_seperator', [
    'type'        => 'custom',
    'settings'    => 'counter_seperate_one',
    'section'     => 'real_estate_salient_pro_home_counter',
    'default'     => '<hr>',
    'priority'    => 2,
    'active_callback'  => [
        [
            'setting'  => 'counter_enable',
            'operator' => '===',
            'value'    => 'enable',
        ]
    ],
] );
real_estate_salient_pro_kirki::add_field( 'real_estate_salient_pro_counter_upload', [
    'type'        => 'image',
    'settings'    => 'counter_upload',
    'label'       => esc_html__( 'Image for background', 'real-estate-salient-pro' ),
    'description' => esc_html__( 'Number count will appear over the image.', 'real-estate-salient-pro' ),
    'section'     => 'real_estate_salient_pro_home_counter',
    'default'     => get_template_directory_uri(). '/img/image.jpg',
    'priority'    => 3,
    'active_callback'  => [
        [
            'setting'  => 'counter_enable',
            'operator' => '===',
            'value'    => 'enable',
        ],
    ],
] );

// seperator
real_estate_salient_pro_kirki::add_field( 'real_estate_salient_pro_counter_seperator', [
    'type'        => 'custom',
    'settings'    => 'counter_seperate_two',
    'section'     => 'real_estate_salient_pro_home_counter',
    'default'     => '<hr>',
    'priority'    => 4,
    'active_callback'  => [
        [
            'setting'  => 'counter_enable',
            'operator' => '===',
            'value'    => 'enable',
        ]
    ],
] );

real_estate_salient_pro_kirki::add_field( 'real_estate_salient_pro_counter_repeater', array(
    'type'        => 'repeater',
    'label'       => esc_html__( 'Counter content', 'real-estate-salient-pro' ),
    //'description' => esc_html__( 'Please create in multiply of 3 for better result.', 'real-estate-salient-pro' ),
    'section'     => 'real_estate_salient_pro_home_counter',
    'priority'    => 5,
    'row_label' => array(
        'type' => 'field',
        'value' => esc_html__('Counter', 'real-estate-salient-pro' ),
        'field' => 'offer_social_icon',
    ),
    'active_callback'  => [
            [
                'setting'  => 'counter_enable',
                'operator' => '===',
                'value'    => 'enable',
            ],
        ],
    'choices' => [
        'limit' => 4
    ],
    'default'      => [
        [
            'counter_icon' => 'list-alt',
            'counter_title'  => esc_html__( 'Properties', 'real-estate-salient-pro' ),
            'counter_count'  => 1232,
        ],
        [
            'counter_icon' => 'money-bill-alt',
            'counter_title'  => esc_html__( 'Customers', 'real-estate-salient-pro' ),
            'counter_count'  => 354,
        ],
        [
            'counter_icon' => 'user',
            'counter_title'  => esc_html__( 'Agents', 'real-estate-salient-pro' ),
            'counter_count'  => 27,
        ],
        [
            'counter_icon' => 'map',
            'counter_title'  => esc_html__( 'Cities', 'real-estate-salient-pro' ),
            'counter_count'  => 12,
        ],
    ],
    'settings'    => 'counter_single',
    'fields' => array(
        'counter_icon' => array(
            'type'        => 'select',
            'label'       => esc_html__( 'FontAwesome Icon', 'real-estate-salient-pro' ),
            'description' => esc_html__( 'Please choose an icon from dropdown list.', 'real-estate-salient-pro' ),
            'default'     => 'facebook',
            'choices'     => array(
                'address-book'      =>  esc_html__( 'Address Book ', 'real-estate-salient-pro' ),
                'address-card'       =>  esc_html__( 'Address Card', 'real-estate-salient-pro' ),
                'angry'      =>  esc_html__( 'Angry', 'real-estate-salient-pro' ),
                'arrow-alt-circle-down'     =>  esc_html__( 'Arrow-alt-circle-down', 'real-estate-salient-pro' ),
                'arrow-alt-circle-left'         =>  esc_html__( 'Arrow-alt-circle-left', 'real-estate-salient-pro' ),
                'arrow-alt-circle-right'      =>  esc_html__( 'Arrow-alt-circle-right', 'real-estate-salient-pro' ),
                'arrow-alt-circle-up'      =>  esc_html__( 'Arrow-alt-circle-up', 'real-estate-salient-pro' ),
                'bell'      =>  esc_html__( 'Bell', 'real-estate-salient-pro' ),
                'bell-slash'      =>  esc_html__( 'Bell-slash', 'real-estate-salient-pro' ),
                'bookmark'      =>  esc_html__( 'Bookmark', 'real-estate-salient-pro' ),
                'building'      =>  esc_html__( 'Building', 'real-estate-salient-pro' ),
                'calendar'      =>  esc_html__( 'Calendar', 'real-estate-salient-pro' ),
                'calendar-alt'      =>  esc_html__( 'Calendar-alt', 'real-estate-salient-pro' ),
                'calendar-check'      =>  esc_html__( 'Calendar-check', 'real-estate-salient-pro' ),
                'calendar-minus'      =>  esc_html__( 'Calendar-minus', 'real-estate-salient-pro' ),
                'calendar-plus'      =>  esc_html__( 'Calendar-plus', 'real-estate-salient-pro' ),
                'calendar-times'      =>  esc_html__( 'Calendar-times', 'real-estate-salient-pro' ),
                'caret-square-down'      =>  esc_html__( 'Caret-square-down', 'real-estate-salient-pro' ),
                'caret-square-left'      =>  esc_html__( 'Caret-square-left', 'real-estate-salient-pro' ),
                'caret-square-right'      =>  esc_html__( 'Caret-square-right', 'real-estate-salient-pro' ),
                'caret-square-up'      =>  esc_html__( 'Caret-square-up', 'real-estate-salient-pro' ),
                'chart-bar'      =>  esc_html__( 'Chart-bar', 'real-estate-salient-pro' ),
                'check-circle'      =>  esc_html__( 'Check-circle', 'real-estate-salient-pro' ),
                'check-square'      =>  esc_html__( 'Check-square', 'real-estate-salient-pro' ),
                'circle'      =>  esc_html__( 'Circle', 'real-estate-salient-pro' ),
                'clipboard'      =>  esc_html__( 'Clipboard', 'real-estate-salient-pro' ),
                'clock'      =>  esc_html__( 'Clock', 'real-estate-salient-pro' ),
                'clone'      =>  esc_html__( 'Clone', 'real-estate-salient-pro' ),
                'closed-captioning'      =>  esc_html__( 'Closed-captioning', 'real-estate-salient-pro' ),
                'comment'      =>  esc_html__( 'Comment', 'real-estate-salient-pro' ),
                'comment-alt'      =>  esc_html__( 'Comment-alt', 'real-estate-salient-pro' ),
                'comment-dots'      =>  esc_html__( 'Comment-dots', 'real-estate-salient-pro' ),
                'comments'      =>  esc_html__( 'Comments', 'real-estate-salient-pro' ),
                'compass'      =>  esc_html__( 'Compass', 'real-estate-salient-pro' ),
                'copy'      =>  esc_html__( 'Copy', 'real-estate-salient-pro' ),
                'copyright'      =>  esc_html__( 'Copyright', 'real-estate-salient-pro' ),
                'credit-card'      =>  esc_html__( 'Credit-card', 'real-estate-salient-pro' ),
                'dizzy'      =>  esc_html__( 'Dizzy', 'real-estate-salient-pro' ),
                'dot-circle'      =>  esc_html__( 'Dot-circle', 'real-estate-salient-pro' ),
                'edit'      =>  esc_html__( 'Edit', 'real-estate-salient-pro' ),
                'envelope'      =>  esc_html__( 'Envelope', 'real-estate-salient-pro' ),
                'envelope-open'      =>  esc_html__( 'Envelope-open', 'real-estate-salient-pro' ),
                'eye'      =>  esc_html__( 'Eye', 'real-estate-salient-pro' ),
                'eye-slash'      =>  esc_html__( 'Eye-slash', 'real-estate-salient-pro' ),
                'file'      =>  esc_html__( 'File', 'real-estate-salient-pro' ),
                'file-alt'      =>  esc_html__( 'File-alt', 'real-estate-salient-pro' ),
                'file-archive'      =>  esc_html__( 'File-archive', 'real-estate-salient-pro' ),
                'file-audio'      =>  esc_html__( 'File-audio', 'real-estate-salient-pro' ),
                'file-code'      =>  esc_html__( 'File-code', 'real-estate-salient-pro' ),
                'file-excel'      =>  esc_html__( 'File-excel', 'real-estate-salient-pro' ),
                'file-image'      =>  esc_html__( 'File-image', 'real-estate-salient-pro' ),
                'file-pdf'      =>  esc_html__( 'file-pdf', 'real-estate-salient-pro' ),
                'file-powerpoint'      =>  esc_html__( 'file-powerpoint', 'real-estate-salient-pro' ),
                'file-video'      =>  esc_html__( 'file-video', 'real-estate-salient-pro' ),
                'file-word'      =>  esc_html__( 'file-word', 'real-estate-salient-pro' ),
                'flag'      =>  esc_html__( 'flag', 'real-estate-salient-pro' ),
                'flushed'      =>  esc_html__( 'flushed', 'real-estate-salient-pro' ),
                'folder'      =>  esc_html__( 'folder', 'real-estate-salient-pro' ),
                'folder-open'      =>  esc_html__( 'folder-open', 'real-estate-salient-pro' ),
                'frown'      =>  esc_html__( 'frown', 'real-estate-salient-pro' ),
                'frown-open'      =>  esc_html__( 'frown-open', 'real-estate-salient-pro' ),
                'futbol'      =>  esc_html__( 'futbol', 'real-estate-salient-pro' ),
                'gem'      =>  esc_html__( 'gem', 'real-estate-salient-pro' ),
                'grimace'      =>  esc_html__( 'grimace', 'real-estate-salient-pro' ),
                'grin'      =>  esc_html__( 'grin', 'real-estate-salient-pro' ),
                'grin-alt'      =>  esc_html__( 'grin-alt', 'real-estate-salient-pro' ),
                'grin-beam'      =>  esc_html__( 'grin-beam', 'real-estate-salient-pro' ),
                'grin-beam-sweat'      =>  esc_html__( 'grin-beam-sweat', 'real-estate-salient-pro' ),
                'grin-hearts'      =>  esc_html__( 'grin-hearts', 'real-estate-salient-pro' ),
                'grin-squint'      =>  esc_html__( 'grin-squint', 'real-estate-salient-pro' ),
                'grin-squint-tears'      =>  esc_html__( 'grin-squint-tears', 'real-estate-salient-pro' ),
                'grin-stars'      =>  esc_html__( 'grin-stars', 'real-estate-salient-pro' ),
                'hand-lizard'      =>  esc_html__( 'hand-lizard', 'real-estate-salient-pro' ),
                'hand-paper'      =>  esc_html__( 'hand-paper', 'real-estate-salient-pro' ),
                'hand-peace'      =>  esc_html__( 'hand-peace', 'real-estate-salient-pro' ),
                'hand-point-down'      =>  esc_html__( 'hand-point-down', 'real-estate-salient-pro' ),
                'hand-point-left'      =>  esc_html__( 'hand-point-left', 'real-estate-salient-pro' ),
                'hand-point-right'      =>  esc_html__( 'hand-point-right', 'real-estate-salient-pro' ),
                'hand-point-up'      =>  esc_html__( 'hand-point-up', 'real-estate-salient-pro' ),
                'hand-pointer'      =>  esc_html__( 'hand-pointer', 'real-estate-salient-pro' ),
                'handshake'      =>  esc_html__( 'handshake', 'real-estate-salient-pro' ),
                'heart'      =>  esc_html__( 'heart', 'real-estate-salient-pro' ),
                'hospital'      =>  esc_html__( 'hospital', 'real-estate-salient-pro' ),
                'hourglass'      =>  esc_html__( 'hourglass', 'real-estate-salient-pro' ),
                'id-card'      =>  esc_html__( 'id-card', 'real-estate-salient-pro' ),
                'image'      =>  esc_html__( 'image', 'real-estate-salient-pro' ),
                'life-ring'      =>  esc_html__( 'life-ring', 'real-estate-salient-pro' ),
                'lightbulb'      =>  esc_html__( 'lightbulb', 'real-estate-salient-pro' ),
                'list-alt'      =>  esc_html__( 'list-alt', 'real-estate-salient-pro' ),
                'map'      =>  esc_html__( 'map', 'real-estate-salient-pro' ),
                'minus-square'      =>  esc_html__( 'minus-square', 'real-estate-salient-pro' ),
                'money-bill-alt'      =>  esc_html__( 'money-bill-alt', 'real-estate-salient-pro' ),
                'object-group'      =>  esc_html__( 'object-group', 'real-estate-salient-pro' ),
                'paper-plane'      =>  esc_html__( 'paper-plane', 'real-estate-salient-pro' ),
                'pause-circle'      =>  esc_html__( 'pause-circle', 'real-estate-salient-pro' ),
                'play-circle'      =>  esc_html__( 'play-circle', 'real-estate-salient-pro' ),
                'plus-square'      =>  esc_html__( 'plus-square', 'real-estate-salient-pro' ),
                'share-square'      =>  esc_html__( 'share-square', 'real-estate-salient-pro' ),
                'snowflake'      =>  esc_html__( 'snowflake', 'real-estate-salient-pro' ),
                'star'      =>  esc_html__( 'star', 'real-estate-salient-pro' ),
                'sticky-note'      =>  esc_html__( 'sticky-note', 'real-estate-salient-pro' ),
                'sun'      =>  esc_html__( 'sun', 'real-estate-salient-pro' ),
                'thumbs-up'      =>  esc_html__( 'thumbs-up', 'real-estate-salient-pro' ),
                'times-circle'      =>  esc_html__( 'times-circle', 'real-estate-salient-pro' ),
                'trash-alt'      =>  esc_html__( 'trash-alt', 'real-estate-salient-pro' ),
                'user'      =>  esc_html__( 'user', 'real-estate-salient-pro' ),
                'user-circle'      =>  esc_html__( 'user-circle', 'real-estate-salient-pro' ),
                'window-maximize'      =>  esc_html__( 'window-maximize', 'real-estate-salient-pro' ),
                'window-restore'      =>  esc_html__( 'window-restore', 'real-estate-salient-pro' ),
            ),
        ),
        'counter_count' => array(
            'type'        => 'number',
            'label'       => esc_html__( 'Count number', 'real-estate-salient-pro' ),
            'default'     => 200,
        ),
        'counter_title' => array(
            'type'        => 'text',
            'label'       => esc_html__( 'Counter title', 'real-estate-salient-pro' ),
        ),
    ),  
) );